### ISSUE TITLE
jstack not found on PATH and No JAVA_HOME setting

### ISSUE THREAD

**Issue by KangXuechao** [fengfu/jtoolkit#1]
hello uncle qu：
     """Error: jstack not found on PATH and No JAVA_HOME setting! Use -s option set jstack path manually""",    that ' s the problem i met when using "1.CPU相关" and then next all functions, pid is ok,  so ...  will the program should find the java bin  base path automaticly ?

**Comment by fengfu** [comment]
issue was fixed, please check again:)
