### ISSUE TITLE
运行JFR报错 同时服务进程crash

### ISSUE THREAD

**Issue by neilgris** [fengfu/jtoolkit#5]
Error reading response: Inappropriate ioctl for device

**Comment by nwpulei** [comment]
https://github.com/jvm-profiling-tools/async-profiler/issues/145

**Comment by fengfu** [comment]
按照jvm-profiling-tools/async-profiler#145 的说明，根据linux内核版本对async-profiler做了个适配，内核版本低于2.6.34及以下会使用特定libasyncProfiler.so文件的async-profiler

**Comment by fengfu** [comment]
关闭问题，如果问题复现，请open这个issue
