### ISSUE TITLE
飞行记录JFR时 java 进程崩溃

### ISSUE THREAD

**Issue by nwpulei** [fengfu/jtoolkit#7]
Linux 2.6.32
错误提示
/bin/java: symbol lookup error: /async-profiler/build/libasyncProfiler.so: undefined symbol: clock_gettime

貌似是撞到了 async-profiler 的已知问题
https://github.com/jvm-profiling-tools/async-profiler/issues/145

**Comment by fengfu** [comment]
把/home/q/jtoolkit/load/async-profiler/build的libasyncProfiler.so换成https://github.com/jvm-profiling-tools/async-profiler/files/2229568/libasyncProfiler.so.zip里面的文件试试呢？

**Comment by fengfu** [comment]
async-profiler根据linux内核版本做了个适配，内核版本低于2.6.34及以下会使用特定libasyncProfiler.so文件的async-profiler。试一下吧

**Comment by fengfu** [comment]
关闭问题，如果复现，请open这个issue并描述问题
